// GENERATED by nice-generate-exports — do not edit by hand
// To update: edit package.exports.json and run `npm run generate-exports`

/** Animated vertical slider component. */

export { default } from "./components/Slider"
export * from "./components/Slider"
